name: "CD (Entrega Contínua): Main Workflow"

env:
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches: [ master, linter ]

jobs:
  deploy: # Job: exemplo
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: Run Deploy
        run:
          yarn add yarn
          yarn install
          yarn deploy:prod

